language: java

jdk:
  - oraclejdk8
  - openjdk7

before_deploy: >
  ant -f build/ant.xml
  
deploy:
  provider: releases
  api_key:
    secure: XUEVH4recWuA+xxjmy+AXeUSEZINSSeDe5xOALAr7rH3DvYGMV2tC4vO33zmOfyevnn2FxiDJLQqewlc/x9cComjCsuBXys8eMXaoEaFB6UIayBx0iilNQ56ItYnbAXz580/oDvJEVPAzXyGuOLhkW7qvwbVq0fXNauAMRUKrYY=
  file:
    - build/target/cloudslang-cli/cslang-cli.zip
    - build/target/cslang-builder/cslang-builder.zip
  skip_cleanup: true
  on:
    repo: CloudSlang/cloud-slang
    tags: true
    branch: master

after_success:
  - mvn clean cobertura:cobertura coveralls:report